faucets:
  test:
    el_rpc: http://anvil:8545
    chain_id: 31337
    tx_cfg:
      # This private key is pre-funded in the default Anvil network.
      private_key: "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
