[book]
title = "Infrastructure" # used to generate the index page
description = "About infrastructure" # used to generate the index page

[output.html]
build-dir = "infra" # defines which subdirectory the book will be deployed to
