[book]
authors = ["Optimism Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Infra Book"

[output.html]
site-url = "/infra/"
git-repository-url = "https://github.com/ethereum-optimism/infra/tree/main/book"
edit-url-template = "https://github.com/ethereum-optimism/infra/tree/main/book/{path}"

